source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Sift' do
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'Alamofire', '~> 3.1'
    pod 'AlamofireImage', '~> 2.0'
    pod 'CTAssetsPickerController',  '~> 3.2.0'
    pod 'ImagePickerSheetController'
    pod 'ALThreeCircleSpinner'
    pod 'ImageCropView', '~> 1.0'
end

pod 'UITextView+Placeholder'
pod 'RNCryptor'
pod 'MBProgressHUD'
pod 'IHKeyboardDismissing'
pod 'IHKeyboardAvoiding'
pod 'TPKeyboardAvoiding'
pod 'ASImageResize'
pod 'ZSWRoundedImage'
pod 'DZNEmptyDataSet'
